---
title: "Testing all pairwise comparisons"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    toc: yes
    toc_float:
      collapsed: true
---


# Prep

```{r, echo=FALSE}

rm(list=ls())

```


```{r,echo=FALSE, message=FALSE}
library(rtracklayer)
library(tidyverse)
library(DiffBind)
library(ComplexHeatmap)
library(UpSetR)
```

## Loading data

```{r}
load("/data/gpfs/projects/punim2745/03.CUTRUN_normalisation_KA/ER_dataset/3.realign_to_human_yeast/R_analysis/2.Diffbind/data/diffbind_analyse_workspace_2v2.RData")
```




```{r}
# Helper filter function to remove non-standard chromosome peaks
keep_standard_chr <- function(df) {
  df %>% filter(grepl("^chr([0-9]+|X|Y)$", seqnames))
}


```

## Wrangling data
```{r}
n_comps = length(dbObj_RLEbackground_list)
  # --- loop over all comparisons and collect counts ---
  all_comps <- map_dfr(1:n_comps, function(comp_no) {
    
background_df      <- dbObj_RLEbackground_list[[comp_no]]  %>% dba.report(th=1) %>% as.data.frame() %>% keep_standard_chr()
RLERiP_df          <- dbObj_RLERiP_list[[comp_no]]         %>% dba.report(th=1) %>% as.data.frame() %>% keep_standard_chr()
RPKM_df            <- dbObj_RPKMnorm_list[[comp_no]]       %>% dba.report(th=1) %>% as.data.frame() %>% keep_standard_chr()
greenlist_df       <- dbObj_greenlist_list[[comp_no]]      %>% dba.report(th=1) %>% as.data.frame() %>% keep_standard_chr()
spikein_dm6_df     <- dbObj_dm6norm_list[[comp_no]]        %>% dba.report(th=1) %>% as.data.frame() %>% keep_standard_chr()
spikein_sacCer3_df <- dbObj_sacCer3norm_list[[comp_no]]    %>% dba.report(th=1) %>% as.data.frame() %>% keep_standard_chr()

    samples    <- colnames(background_df)[7:8] %>% gsub("Conc_", "", .)
    comp_label <- paste(samples[1], "vs", samples[2])

    tibble(
      comparison  = comp_label,
      norm_method = c("background", "RiP", "RPKM", "greenlist", "dm6", "sacCer3"),
      up   = c(
        sum(background_df$Fold > 0      & background_df$FDR < 0.05),
        sum(RLERiP_df$Fold > 0          & RLERiP_df$FDR < 0.05),
        sum(RPKM_df$Fold > 0            & RPKM_df$FDR < 0.05),
        sum(greenlist_df$Fold > 0       & greenlist_df$FDR < 0.05),
        sum(spikein_dm6_df$Fold > 0     & spikein_dm6_df$FDR < 0.05),
        sum(spikein_sacCer3_df$Fold > 0 & spikein_sacCer3_df$FDR < 0.05)
      ),
      down = -c(
        sum(background_df$Fold < 0      & background_df$FDR < 0.05),
        sum(RLERiP_df$Fold < 0          & RLERiP_df$FDR < 0.05),
        sum(RPKM_df$Fold < 0            & RPKM_df$FDR < 0.05),
        sum(greenlist_df$Fold < 0       & greenlist_df$FDR < 0.05),
        sum(spikein_dm6_df$Fold < 0     & spikein_dm6_df$FDR < 0.05),
        sum(spikein_sacCer3_df$Fold < 0 & spikein_sacCer3_df$FDR < 0.05)
      )
    )
  })

  
  # --- order comparisons by highest-to-lowest average up peaks ---
  comp_order <- all_comps %>%
    group_by(comparison) %>%
    summarise(mean_up = mean(up), .groups = "drop") %>%
    arrange(desc(mean_up)) %>%
    pull(comparison)

all_comps$norm_method <- all_comps$norm_method %>% gsub("RPKM","Library size",.) %>% gsub("background", "Background",.) %>% gsub("greenlist", "Greenlist", .) %>% gsub("RiP", "Reads in peak",.) %>% gsub("sacCer3", "sacCer3 spike-in",.) %>% gsub("dm6", "dm6 spike-in",.)
  
  
  
  all_comps <- all_comps %>%
    pivot_longer(c(up, down), names_to = "direction", values_to = "count") %>%
    mutate(
      norm_method = factor(norm_method, levels = c("Background", "Library size", "Greenlist", "sacCer3 spike-in", "dm6 spike-in", "Reads in peak")),
      direction   = factor(direction, levels = c("up", "down")),
      comparison  = factor(comparison, levels = comp_order)
    )
```


# Plotting

```{r, fig.width=10, fig.height=6}


# --- plot ---
plot_diff <-   ggplot(all_comps, aes(x = norm_method, y = count, fill = norm_method)) +
    geom_bar(stat = "identity",
             position = position_dodge(width = 0.85),
             width = 0.75, color = "black") +
    geom_hline(yintercept = 0, linewidth = 0.6, colour = "black") +
    geom_text(aes(label = abs(count),
                  vjust = ifelse(direction == "up", -0.4, 1.4)),
              position = position_dodge(width = 0.85),
              size = 3) +
    scale_fill_manual(values = c(
      "Background"       = "#D55E00",
      "Reads in peak"    = "#e25759",
      "Library size"     = "#7E4794",
      "Greenlist"        = "#59a89c",
      "dm6 spike-in"     = "#0b81a2",
      "sacCer3 spike-in" = "#f0c571"
    )) +
    scale_y_continuous(labels = abs) +
facet_wrap(~ comparison, strip.position = "top", ncol = 6) + 
  labs(
      title = "Differential up-regulated and down-regulated peaks across all comparisons",
      x     = "Comparison",
      y     = "Number of differential peaks",
      fill  = "Normalisation method"
    ) +
    theme_bw() +
    theme(
      plot.title           = element_text(hjust = 0.5),
      strip.placement      = "outside",
      strip.text           = element_text(size = 8, face = "bold"),
      legend.position      = "top",
      legend.direction     = "horizontal",
      legend.background    = element_rect(fill = alpha("white", 0.8), colour = NA),
      legend.margin        = margin(4, 4, 4, 4),
      axis.text.x          = element_blank(),
      axis.ticks.x         = element_blank()
    )

  
plot_diff
```


```{r, eval=FALSE}

pdf("differential_peaks_plot.pdf", width = 10, height = 6)
plot_diff
dev.off()

```
